"""add auth columns to users

Revision ID: 4ffb66cc6815
Revises: 5271c1426d30
Create Date: 2026-06-13 01:11:29.273396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4ffb66cc6815'
down_revision: Union[str, None] = '5271c1426d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('users', sa.Column('must_reset_password', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.alter_column('users', 'is_active', server_default=None)
    op.alter_column('users', 'must_reset_password', server_default=None)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'must_reset_password')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
